from .bus import (
    DOMAIN,
    NTC5K_TEMPERATURES,
    BUS_ADDRESSES,
    FANSPEEDS,
    COMPONENT_FAULTS,
    REGISTERS_AND_COILS,
)

from .config import (
    CONF_HOUSE_AREA,
    CONF_HOUSE_VOLUME,
    CONF_ISOLATION_FACTOR,
    CONF_AIRFLOW_PER_MODE,
    CONF_MAX_AIRFLOW,
    CONF_POWER_PER_MODE,
    CONF_MAX_POWER,
    CONF_HEATING_POWER,
    CONF_DEVICE_MODEL,
    CUSTOM_MODEL,
    DEVICE_PRESETS,
    CONF_ENTITY_PREFIX,
    DEFAULT_ENTITY_PREFIX,
)

from .entities import (
    SENSOR_ENTITIES,
    BINARY_SENSOR_ENTITIES,
    NUMBER_ENTITIES,
    SWITCH_ENTITIES,
    SELECT_ENTITIES,
)

from .helpers import (
    LOVELACE_DEVICE_SELECT_KEY,
    LOVELACE_DEVICE_SELECT_NAME,
    LOVELACE_DEVICE_SELECT_UNIQUE_ID,
    LOVELACE_DEVICE_SELECT_OBJECT_ID,
    UI_NUMBER_ENTITIES,
    RH_SENSOR_KEYS,
    RH_NUMBER_KEYS,
    RH_SELECT_KEYS,
    CO2_NUMBER_KEYS,
    CO2_SENSOR_KEYS,
    INTERNAL_SENSOR_KEYS,
    INTERNAL_BINARY_SENSOR_KEYS,
    SOFTBOOST_STORAGE_VERSION,
    SOFTBOOST_STORAGE_KEY_SUFFIX,
    DEFAULT_SOFTBOOST_LEVEL,
    DEFAULT_SOFTBOOST_DURATION_SECONDS,
    FIREPLACE_RESTORE_DELAY_SECONDS,
    SOFTBOOST_NUMBER_ENTITIES,
    SOFTBOOST_SWITCH_ENTITIES,
    DEVELOPER_MODE,
)

# avoid collision of dev and production integrations
if DEVELOPER_MODE:
    BUS_ADDRESSES = {
        **BUS_ADDRESSES,
        "_HA": 0x2D,
    }
