from .bus import (
    DOMAIN,
    NTC5K_TEMPERATURES,
    BUS_ADDRESSES,
    FANSPEEDS,
    COMPONENT_FAULTS,
    REGISTERS_AND_COILS,
)

from .config import (
    CONF_HOUSE_AREA,
    CONF_HOUSE_VOLUME,
    CONF_ISOLATION_FACTOR,
    CONF_AIRFLOW_PER_MODE,
    CONF_MAX_AIRFLOW,
    CONF_POWER_PER_MODE,
    CONF_MAX_POWER,
    CONF_HEATING_POWER,
    CONF_DEVICE_MODEL,
    CUSTOM_MODEL,
    DEVICE_PRESETS,
    CONF_ENTITY_PREFIX,
    DEFAULT_ENTITY_PREFIX,
)

from .entities import (
    SENSOR_ENTITIES,
    BINARY_SENSOR_ENTITIES,
    NUMBER_ENTITIES,
    SWITCH_ENTITIES,
    SELECT_ENTITIES,
)

from .helpers import (
    LOVELACE_DEVICE_SELECT_KEY,
    LOVELACE_DEVICE_SELECT_NAME,
    LOVELACE_DEVICE_SELECT_UNIQUE_ID,
    LOVELACE_DEVICE_SELECT_OBJECT_ID,
    UI_NUMBER_ENTITIES,
)

# please ignore
# needed for testing rH/CO2 formulas and settings without having sensors installed
DEVELOPER_MODE = False
try:
    from .local_dev import DEVELOPER_MODE as LOCAL_DEVELOPER_MODE
    DEVELOPER_MODE = LOCAL_DEVELOPER_MODE
except ImportError:
    pass